import {
  RECORDING_AUDIO_MODES,
  RECORDING_BITRATES,
  RECORDING_BUFFER_STORAGE,
  RECORDING_ENCODERS,
  RECORDING_FRAME_RATES,
  RECORDING_RESOLUTIONS,
} from "@alloy/contracts"

export { alloyDesktop } from "@/lib/desktop"
export type { DesktopSavedServer } from "@/lib/desktop"

export const DESKTOP_RECORDING_ENCODERS = RECORDING_ENCODERS

export const DESKTOP_RECORDING_RESOLUTIONS = RECORDING_RESOLUTIONS
export const DESKTOP_RECORDING_FRAME_RATES = RECORDING_FRAME_RATES
export const DESKTOP_RECORDING_BITRATES = RECORDING_BITRATES
export const DESKTOP_RECORDING_AUDIO_MODES = RECORDING_AUDIO_MODES

export const DESKTOP_RECORDING_BUFFER_STORAGE = RECORDING_BUFFER_STORAGE
