import {
  RECORDING_AUDIO_DEVICE_KINDS,
  RECORDING_AUDIO_MODES,
  RECORDING_BITRATES,
  RECORDING_BUFFER_STORAGE,
  RECORDING_CODECS,
  RECORDING_ENCODERS,
  RECORDING_FRAME_RATES,
  RECORDING_QUALITY_PRESETS,
  RECORDING_RESOLUTIONS,
  RECORDING_TRIGGER_MODES,
} from "alloy-contracts"

import {
  alloyDesktop as readAlloyDesktop,
  type AlloyDesktop,
  type DesktopSavedServer,
} from "@/lib/desktop"

export type { DesktopSavedServer }

export const DESKTOP_RECORDING_ENCODERS = RECORDING_ENCODERS
export const DESKTOP_RECORDING_CODECS = RECORDING_CODECS
export const DESKTOP_RECORDING_RESOLUTIONS = RECORDING_RESOLUTIONS
export const DESKTOP_RECORDING_FRAME_RATES = RECORDING_FRAME_RATES
export const DESKTOP_RECORDING_BITRATES = RECORDING_BITRATES
export const DESKTOP_RECORDING_AUDIO_MODES = RECORDING_AUDIO_MODES
export const DESKTOP_RECORDING_AUDIO_DEVICE_KINDS = RECORDING_AUDIO_DEVICE_KINDS
export const DESKTOP_RECORDING_BUFFER_STORAGE = RECORDING_BUFFER_STORAGE
export const DESKTOP_RECORDING_TRIGGER_MODES = RECORDING_TRIGGER_MODES
export const DESKTOP_RECORDING_QUALITY_PRESETS = RECORDING_QUALITY_PRESETS

export function alloyDesktop(): AlloyDesktop | null {
  return readAlloyDesktop()
}
