/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as appAppRouteImport } from './routes/(app)/_app'
import { Route as appAppIndexRouteImport } from './routes/(app)/_app.index'
import { Route as authAuthSignUpRouteImport } from './routes/(auth)/_auth.sign-up'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'
import { Route as appAppSettingsRouteImport } from './routes/(app)/_app.settings'
import { Route as appAppGamesRouteImport } from './routes/(app)/_app.games'
import { Route as appAppLibraryIndexRouteImport } from './routes/(app)/_app.library.index'
import { Route as appAppGamesIndexRouteImport } from './routes/(app)/_app.games.index'
import { Route as appAppUUsernameRouteImport } from './routes/(app)/_app.u.$username'
import { Route as appAppTagsTagRouteImport } from './routes/(app)/_app.tags.$tag'
import { Route as appAppLibraryCaptureIdRouteImport } from './routes/(app)/_app.library.$captureId'
import { Route as appAppGamesGameIdRouteImport } from './routes/(app)/_app.games.$gameId'
import { Route as appAppGSlugRouteImport } from './routes/(app)/_app.g.$slug'
import { Route as appAppUUsernameIndexRouteImport } from './routes/(app)/_app.u.$username.index'
import { Route as appAppUUsernameTaggedRouteImport } from './routes/(app)/_app.u.$username.tagged'
import { Route as appAppUUsernameLikedRouteImport } from './routes/(app)/_app.u.$username.liked'
import { Route as appAppUUsernameFeedRouteImport } from './routes/(app)/_app.u.$username.feed'
import { Route as appAppUUsernameAllRouteImport } from './routes/(app)/_app.u.$username.all'
import { Route as appAppLibraryCClipIdRouteImport } from './routes/(app)/_app.library.c.$clipId'
import { Route as appAppGamesGameIdCClipIdRouteImport } from './routes/(app)/_app.games.$gameId.c.$clipId'
import { Route as appAppGSlugCClipIdRouteImport } from './routes/(app)/_app.g.$slug.c.$clipId'

const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: '/(app)/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppIndexRoute = appAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppRoute,
} as any)
const authAuthSignUpRoute = authAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)
const appAppSettingsRoute = appAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appAppRoute,
} as any)
const appAppGamesRoute = appAppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => appAppRoute,
} as any)
const appAppLibraryIndexRoute = appAppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => appAppRoute,
} as any)
const appAppGamesIndexRoute = appAppGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppGamesRoute,
} as any)
const appAppUUsernameRoute = appAppUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => appAppRoute,
} as any)
const appAppTagsTagRoute = appAppTagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => appAppRoute,
} as any)
const appAppLibraryCaptureIdRoute = appAppLibraryCaptureIdRouteImport.update({
  id: '/library/$captureId',
  path: '/library/$captureId',
  getParentRoute: () => appAppRoute,
} as any)
const appAppGamesGameIdRoute = appAppGamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => appAppGamesRoute,
} as any)
const appAppGSlugRoute = appAppGSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => appAppRoute,
} as any)
const appAppUUsernameIndexRoute = appAppUUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppUUsernameRoute,
} as any)
const appAppUUsernameTaggedRoute = appAppUUsernameTaggedRouteImport.update({
  id: '/tagged',
  path: '/tagged',
  getParentRoute: () => appAppUUsernameRoute,
} as any)
const appAppUUsernameLikedRoute = appAppUUsernameLikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => appAppUUsernameRoute,
} as any)
const appAppUUsernameFeedRoute = appAppUUsernameFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => appAppUUsernameRoute,
} as any)
const appAppUUsernameAllRoute = appAppUUsernameAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => appAppUUsernameRoute,
} as any)
const appAppLibraryCClipIdRoute = appAppLibraryCClipIdRouteImport.update({
  id: '/library/c/$clipId',
  path: '/library/c/$clipId',
  getParentRoute: () => appAppRoute,
} as any)
const appAppGamesGameIdCClipIdRoute =
  appAppGamesGameIdCClipIdRouteImport.update({
    id: '/c/$clipId',
    path: '/c/$clipId',
    getParentRoute: () => appAppGamesGameIdRoute,
  } as any)
const appAppGSlugCClipIdRoute = appAppGSlugCClipIdRouteImport.update({
  id: '/c/$clipId',
  path: '/c/$clipId',
  getParentRoute: () => appAppGSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/setup': typeof authSetupRoute
  '/games': typeof appAppGamesRouteWithChildren
  '/settings': typeof appAppSettingsRoute
  '/login': typeof authAuthLoginRoute
  '/sign-up': typeof authAuthSignUpRoute
  '/': typeof appAppIndexRoute
  '/g/$slug': typeof appAppGSlugRouteWithChildren
  '/games/$gameId': typeof appAppGamesGameIdRouteWithChildren
  '/library/$captureId': typeof appAppLibraryCaptureIdRoute
  '/tags/$tag': typeof appAppTagsTagRoute
  '/u/$username': typeof appAppUUsernameRouteWithChildren
  '/games/': typeof appAppGamesIndexRoute
  '/library/': typeof appAppLibraryIndexRoute
  '/library/c/$clipId': typeof appAppLibraryCClipIdRoute
  '/u/$username/all': typeof appAppUUsernameAllRoute
  '/u/$username/feed': typeof appAppUUsernameFeedRoute
  '/u/$username/liked': typeof appAppUUsernameLikedRoute
  '/u/$username/tagged': typeof appAppUUsernameTaggedRoute
  '/u/$username/': typeof appAppUUsernameIndexRoute
  '/g/$slug/c/$clipId': typeof appAppGSlugCClipIdRoute
  '/games/$gameId/c/$clipId': typeof appAppGamesGameIdCClipIdRoute
}
export interface FileRoutesByTo {
  '/setup': typeof authSetupRoute
  '/settings': typeof appAppSettingsRoute
  '/login': typeof authAuthLoginRoute
  '/sign-up': typeof authAuthSignUpRoute
  '/': typeof appAppIndexRoute
  '/g/$slug': typeof appAppGSlugRouteWithChildren
  '/games/$gameId': typeof appAppGamesGameIdRouteWithChildren
  '/library/$captureId': typeof appAppLibraryCaptureIdRoute
  '/tags/$tag': typeof appAppTagsTagRoute
  '/games': typeof appAppGamesIndexRoute
  '/library': typeof appAppLibraryIndexRoute
  '/library/c/$clipId': typeof appAppLibraryCClipIdRoute
  '/u/$username/all': typeof appAppUUsernameAllRoute
  '/u/$username/feed': typeof appAppUUsernameFeedRoute
  '/u/$username/liked': typeof appAppUUsernameLikedRoute
  '/u/$username/tagged': typeof appAppUUsernameTaggedRoute
  '/u/$username': typeof appAppUUsernameIndexRoute
  '/g/$slug/c/$clipId': typeof appAppGSlugCClipIdRoute
  '/games/$gameId/c/$clipId': typeof appAppGamesGameIdCClipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/setup': typeof authSetupRoute
  '/(app)/_app/games': typeof appAppGamesRouteWithChildren
  '/(app)/_app/settings': typeof appAppSettingsRoute
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(auth)/_auth/sign-up': typeof authAuthSignUpRoute
  '/(app)/_app/': typeof appAppIndexRoute
  '/(app)/_app/g/$slug': typeof appAppGSlugRouteWithChildren
  '/(app)/_app/games/$gameId': typeof appAppGamesGameIdRouteWithChildren
  '/(app)/_app/library/$captureId': typeof appAppLibraryCaptureIdRoute
  '/(app)/_app/tags/$tag': typeof appAppTagsTagRoute
  '/(app)/_app/u/$username': typeof appAppUUsernameRouteWithChildren
  '/(app)/_app/games/': typeof appAppGamesIndexRoute
  '/(app)/_app/library/': typeof appAppLibraryIndexRoute
  '/(app)/_app/library/c/$clipId': typeof appAppLibraryCClipIdRoute
  '/(app)/_app/u/$username/all': typeof appAppUUsernameAllRoute
  '/(app)/_app/u/$username/feed': typeof appAppUUsernameFeedRoute
  '/(app)/_app/u/$username/liked': typeof appAppUUsernameLikedRoute
  '/(app)/_app/u/$username/tagged': typeof appAppUUsernameTaggedRoute
  '/(app)/_app/u/$username/': typeof appAppUUsernameIndexRoute
  '/(app)/_app/g/$slug/c/$clipId': typeof appAppGSlugCClipIdRoute
  '/(app)/_app/games/$gameId/c/$clipId': typeof appAppGamesGameIdCClipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/setup'
    | '/games'
    | '/settings'
    | '/login'
    | '/sign-up'
    | '/'
    | '/g/$slug'
    | '/games/$gameId'
    | '/library/$captureId'
    | '/tags/$tag'
    | '/u/$username'
    | '/games/'
    | '/library/'
    | '/library/c/$clipId'
    | '/u/$username/all'
    | '/u/$username/feed'
    | '/u/$username/liked'
    | '/u/$username/tagged'
    | '/u/$username/'
    | '/g/$slug/c/$clipId'
    | '/games/$gameId/c/$clipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/settings'
    | '/login'
    | '/sign-up'
    | '/'
    | '/g/$slug'
    | '/games/$gameId'
    | '/library/$captureId'
    | '/tags/$tag'
    | '/games'
    | '/library'
    | '/library/c/$clipId'
    | '/u/$username/all'
    | '/u/$username/feed'
    | '/u/$username/liked'
    | '/u/$username/tagged'
    | '/u/$username'
    | '/g/$slug/c/$clipId'
    | '/games/$gameId/c/$clipId'
  id:
    | '__root__'
    | '/(app)/_app'
    | '/(auth)/_auth'
    | '/(auth)/setup'
    | '/(app)/_app/games'
    | '/(app)/_app/settings'
    | '/(auth)/_auth/login'
    | '/(auth)/_auth/sign-up'
    | '/(app)/_app/'
    | '/(app)/_app/g/$slug'
    | '/(app)/_app/games/$gameId'
    | '/(app)/_app/library/$captureId'
    | '/(app)/_app/tags/$tag'
    | '/(app)/_app/u/$username'
    | '/(app)/_app/games/'
    | '/(app)/_app/library/'
    | '/(app)/_app/library/c/$clipId'
    | '/(app)/_app/u/$username/all'
    | '/(app)/_app/u/$username/feed'
    | '/(app)/_app/u/$username/liked'
    | '/(app)/_app/u/$username/tagged'
    | '/(app)/_app/u/$username/'
    | '/(app)/_app/g/$slug/c/$clipId'
    | '/(app)/_app/games/$gameId/c/$clipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
  authSetupRoute: typeof authSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_app/': {
      id: '/(app)/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAppIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(auth)/_auth/sign-up': {
      id: '/(auth)/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authAuthSignUpRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(app)/_app/settings': {
      id: '/(app)/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appAppSettingsRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/games': {
      id: '/(app)/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof appAppGamesRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/library/': {
      id: '/(app)/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof appAppLibraryIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/games/': {
      id: '/(app)/_app/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof appAppGamesIndexRouteImport
      parentRoute: typeof appAppGamesRoute
    }
    '/(app)/_app/u/$username': {
      id: '/(app)/_app/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof appAppUUsernameRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/tags/$tag': {
      id: '/(app)/_app/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof appAppTagsTagRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/library/$captureId': {
      id: '/(app)/_app/library/$captureId'
      path: '/library/$captureId'
      fullPath: '/library/$captureId'
      preLoaderRoute: typeof appAppLibraryCaptureIdRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/games/$gameId': {
      id: '/(app)/_app/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof appAppGamesGameIdRouteImport
      parentRoute: typeof appAppGamesRoute
    }
    '/(app)/_app/g/$slug': {
      id: '/(app)/_app/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof appAppGSlugRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/u/$username/': {
      id: '/(app)/_app/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof appAppUUsernameIndexRouteImport
      parentRoute: typeof appAppUUsernameRoute
    }
    '/(app)/_app/u/$username/tagged': {
      id: '/(app)/_app/u/$username/tagged'
      path: '/tagged'
      fullPath: '/u/$username/tagged'
      preLoaderRoute: typeof appAppUUsernameTaggedRouteImport
      parentRoute: typeof appAppUUsernameRoute
    }
    '/(app)/_app/u/$username/liked': {
      id: '/(app)/_app/u/$username/liked'
      path: '/liked'
      fullPath: '/u/$username/liked'
      preLoaderRoute: typeof appAppUUsernameLikedRouteImport
      parentRoute: typeof appAppUUsernameRoute
    }
    '/(app)/_app/u/$username/feed': {
      id: '/(app)/_app/u/$username/feed'
      path: '/feed'
      fullPath: '/u/$username/feed'
      preLoaderRoute: typeof appAppUUsernameFeedRouteImport
      parentRoute: typeof appAppUUsernameRoute
    }
    '/(app)/_app/u/$username/all': {
      id: '/(app)/_app/u/$username/all'
      path: '/all'
      fullPath: '/u/$username/all'
      preLoaderRoute: typeof appAppUUsernameAllRouteImport
      parentRoute: typeof appAppUUsernameRoute
    }
    '/(app)/_app/library/c/$clipId': {
      id: '/(app)/_app/library/c/$clipId'
      path: '/library/c/$clipId'
      fullPath: '/library/c/$clipId'
      preLoaderRoute: typeof appAppLibraryCClipIdRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/_app/games/$gameId/c/$clipId': {
      id: '/(app)/_app/games/$gameId/c/$clipId'
      path: '/c/$clipId'
      fullPath: '/games/$gameId/c/$clipId'
      preLoaderRoute: typeof appAppGamesGameIdCClipIdRouteImport
      parentRoute: typeof appAppGamesGameIdRoute
    }
    '/(app)/_app/g/$slug/c/$clipId': {
      id: '/(app)/_app/g/$slug/c/$clipId'
      path: '/c/$clipId'
      fullPath: '/g/$slug/c/$clipId'
      preLoaderRoute: typeof appAppGSlugCClipIdRouteImport
      parentRoute: typeof appAppGSlugRoute
    }
  }
}

interface appAppGamesGameIdRouteChildren {
  appAppGamesGameIdCClipIdRoute: typeof appAppGamesGameIdCClipIdRoute
}

const appAppGamesGameIdRouteChildren: appAppGamesGameIdRouteChildren = {
  appAppGamesGameIdCClipIdRoute: appAppGamesGameIdCClipIdRoute,
}

const appAppGamesGameIdRouteWithChildren =
  appAppGamesGameIdRoute._addFileChildren(appAppGamesGameIdRouteChildren)

interface appAppGamesRouteChildren {
  appAppGamesGameIdRoute: typeof appAppGamesGameIdRouteWithChildren
  appAppGamesIndexRoute: typeof appAppGamesIndexRoute
}

const appAppGamesRouteChildren: appAppGamesRouteChildren = {
  appAppGamesGameIdRoute: appAppGamesGameIdRouteWithChildren,
  appAppGamesIndexRoute: appAppGamesIndexRoute,
}

const appAppGamesRouteWithChildren = appAppGamesRoute._addFileChildren(
  appAppGamesRouteChildren,
)

interface appAppGSlugRouteChildren {
  appAppGSlugCClipIdRoute: typeof appAppGSlugCClipIdRoute
}

const appAppGSlugRouteChildren: appAppGSlugRouteChildren = {
  appAppGSlugCClipIdRoute: appAppGSlugCClipIdRoute,
}

const appAppGSlugRouteWithChildren = appAppGSlugRoute._addFileChildren(
  appAppGSlugRouteChildren,
)

interface appAppUUsernameRouteChildren {
  appAppUUsernameAllRoute: typeof appAppUUsernameAllRoute
  appAppUUsernameFeedRoute: typeof appAppUUsernameFeedRoute
  appAppUUsernameLikedRoute: typeof appAppUUsernameLikedRoute
  appAppUUsernameTaggedRoute: typeof appAppUUsernameTaggedRoute
  appAppUUsernameIndexRoute: typeof appAppUUsernameIndexRoute
}

const appAppUUsernameRouteChildren: appAppUUsernameRouteChildren = {
  appAppUUsernameAllRoute: appAppUUsernameAllRoute,
  appAppUUsernameFeedRoute: appAppUUsernameFeedRoute,
  appAppUUsernameLikedRoute: appAppUUsernameLikedRoute,
  appAppUUsernameTaggedRoute: appAppUUsernameTaggedRoute,
  appAppUUsernameIndexRoute: appAppUUsernameIndexRoute,
}

const appAppUUsernameRouteWithChildren = appAppUUsernameRoute._addFileChildren(
  appAppUUsernameRouteChildren,
)

interface appAppRouteChildren {
  appAppGamesRoute: typeof appAppGamesRouteWithChildren
  appAppSettingsRoute: typeof appAppSettingsRoute
  appAppIndexRoute: typeof appAppIndexRoute
  appAppGSlugRoute: typeof appAppGSlugRouteWithChildren
  appAppLibraryCaptureIdRoute: typeof appAppLibraryCaptureIdRoute
  appAppTagsTagRoute: typeof appAppTagsTagRoute
  appAppUUsernameRoute: typeof appAppUUsernameRouteWithChildren
  appAppLibraryIndexRoute: typeof appAppLibraryIndexRoute
  appAppLibraryCClipIdRoute: typeof appAppLibraryCClipIdRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppGamesRoute: appAppGamesRouteWithChildren,
  appAppSettingsRoute: appAppSettingsRoute,
  appAppIndexRoute: appAppIndexRoute,
  appAppGSlugRoute: appAppGSlugRouteWithChildren,
  appAppLibraryCaptureIdRoute: appAppLibraryCaptureIdRoute,
  appAppTagsTagRoute: appAppTagsTagRoute,
  appAppUUsernameRoute: appAppUUsernameRouteWithChildren,
  appAppLibraryIndexRoute: appAppLibraryIndexRoute,
  appAppLibraryCClipIdRoute: appAppLibraryCClipIdRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignUpRoute: typeof authAuthSignUpRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignUpRoute: authAuthSignUpRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
  authSetupRoute: authSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
